### PR TITLE
Fix helper function return type

### PR DESCRIPTION
**Pull request by PavelCz**
👀

### CODE REVIEW

**Comment by PavelCz** [comment]
Hope you're using Python 3.9+

**Comment by jstmn** [comment]
This is still on 3.8 :) 

can you change to `from typing import Union, Tuple` and  `def _get_device() -> Tuple[str, int]`

- jeremy

**Comment by PavelCz** [comment]
@jstmn Done

**Comment by jstmn** [comment]
lgtm! thanks

**Pull request merged**
